---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: public
  label: Public directory
  create: all
  match: "**/*"
- type: heading
  label: Portrait
- type: document
  path: public/images
  label: Icon
  read_only: true
- type: heading
  label: Couple
- type: heading
  label: Baptême
- type: heading
  label: Famille
- type: heading
  label: Bébé
- type: heading
  label: Grossesse
- type: heading
  label: Mariage
upload_dir: public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
