---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Images
- type: directory
  path: public/images/gallery
  label: Gallery Images
  create: all
  match: "**/*"
upload_dir: public/assets/gallery
public_path: "/assets/gallery"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
